apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: ds-h-01
  namespace: fleet-default
spec:
  defaultPodSecurityAdmissionConfigurationTemplateName: rancher-restricted
  kubernetesVersion: v1.27.8+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-cilium:
        cilium:
          ipv6:
            enabled: true
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
        operator:
          replicas: 1
    etcd:
      s3:
        bucket: rancher-backups
        cloudCredentialName: cattle-global-data:s3-credentials
        endpoint: s3.brynnharrison.com
        folder: ds-h-01
        region: eu-west-2
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: cilium
      disable-kube-proxy: false
      etcd-expose-metrics: false
      kube-apiserver-arg:
        - >-
          admission-control-config-file=/etc/rancher/rke2/config/rancher-psact.yaml
    machinePoolDefaults: {}
    machineSelectorConfig:
      - config:
          profile: cis-1.23
          protect-kernel-defaults: true
    machineSelectorFiles:
      - fileSources:
          - configMap:
              name: ''
            secret:
              items:
                - hash: XTHEF2B5RKKEchq1kPEPl4TBMSZmBWet+3EHDzy7Tsg=
                  key: admission-config-psact
                  path: /etc/rancher/rke2/config/rancher-psact.yaml
              name: ds-h-01-admission-configuration-psact
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
    registries:
      configs:
        harbor.brynnharrison.com:
          authConfigSecretName: registryconfig-auth-qksk5
      mirrors:
        docker.io:
          endpoint:
            - https://harbor.brynnharrison.com
          rewrite:
            (.*): docker.io/$1
        gcr.io:
          endpoint:
            - https://harbor.brynnharrison.com
          rewrite:
            (.*): gcr.io/$1
        ghcr.io:
          endpoint:
            - https://harbor.brynnharrison.com
          rewrite:
            (.*): ghcr.io/$1
        k8s.gcr.io:
          endpoint:
            - https://harbor.brynnharrison.com
          rewrite:
            (.*): k8s.gcr.io/$1
        quay.io:
          endpoint:
            - https://harbor.brynnharrison.com
          rewrite:
            (.*): quay.io/$1
        registry.rancher.com:
          endpoint:
            - https://harbor.brynnharrison.com
          rewrite:
            (.*): registry.rancher.com/$1
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
